services:
  - type: web
    name: apl-payyyy
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: SMTP_FROM_NAME
        sync: false
      - key: EDFA_MERCHANT_ID
        sync: false
      - key: EDFA_MERCHANT_PASSWORD
        sync: false
      - key: EDFA_CURRENCY
        sync: false
      - key: EDFA_COUNTRY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: AES_ENCRYPTION_KEY
        sync: false
